export const site = {
  name: "Serigne Saliou SENE",
  title: "Développeur Backend Symfony · Île-de-France",
  description:
    "Ingénieur Backend spécialisé Symfony, API Platform et Drupal. Expertise en performance, qualité logicielle, sécurité API et industrialisation CI/CD. Disponible pour missions backend en France.",
  url: "https://serigne-saliou-sene.vercel.app",
  locale: "fr_FR",
  email: "serignesaliou.sene@outlook.fr",
  phone: "+33 6 16 26 72 92",
  location: "Sarcelles / Île-de-France",
  github: "https://github.com/ss-sene",
  linkedin: "https://www.linkedin.com/in/serignesaliousene",
  keywords: [
    "ingénieur backend",
    "PHP",
    "Symfony",
    "API Platform",
    "Drupal",
    "API REST",
    "CI/CD",
    "optimisation SQL",
    "PostgreSQL",
    "performance backend",
    "qualité logicielle",
    "Île-de-France",
  ],
} as const;
